language: cpp
compiler:
  - g++
os:
- linux
before_script:
- echo 'before_script'
script: make all
after_success:
- echo 'after_success'
- chmod 775 test
- ./test
after_failure:
 echo 'after_failed'

after_script:
- echo 'after_script'
