language: cpp
compiler:
  - g++
os:
- linux
before_script:
- echo '==============================='
script: make all
after_success:
- echo 'success'
- chmod 775 test
- ./test
after_failure:
 echo 'failed'
