language: cpp
compiler:
  - g++
os:
- linux
before_script:
- echo '==============================='
- echo $LANG
- echo $LC_ALL
- echo '==============================='
script: make all
after_success:
 echo 'success'
 test
after_failure:
 echo 'failed'
