language: cpp
compiler:
  - clang
  - gcc
os:
- linux
before_script:
- echo '==============================='
- echo $LANG
- echo $LC_ALL
- echo '==============================='
script: make all
after_success:
 echo 'success'
after_failure:
 echo 'failed'
